from . import prestashop_binding
from . import prestashop_backend
from . import prestashop_shop
from . import product_category
from . import product_template
from . import product_product
from . import res_partner
from . import sale_order
from . import stock_picking
from . import prestashop_order_sync_service