# -*- coding: utf-8 -*-
{
    'name': 'Open HRMS Loan Management',
    'version': '17.0.1.0.0',
    'category': 'Human Resources',
    'summary': 'Manage Employee Loan Requests',
    'description': """This module facilitates the creation and management of employee loan requests. 
    The loan amount is automatically deducted from the salary""",
    'author': "Cybrosys Techno Solutions,Open HRMS",
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'live_test_url': 'https://youtu.be/lAT5cqVZTZI',
    'website': "https://cybrosys.com, https://www.openhrms.com",
    'depends': ['hr', 'account', 'payroll'],
    'data': [
        'security/hr_loan_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'wizards/hr_loan_auto_add_employees_wizard.xml',
        'views/hr_loan_views.xml',
        'views/hr_payslip_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_loan_auto_config.xml',
        'views/hr_loan_batch_views.xml',
        'views/menus.xml',
    ],
    'demo': ['data/hr_salary_rule_demo.xml',
             'data/hr_rule_input_demo.xml', ],
    'images': ['static/description/banner.jpg'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
