{
    'name': 'Shopee Connector',
    'version': '17.0.1.0.0',
    'category': 'Connector',
    'summary': 'Connect Odoo with Shopee Marketplace',
    'author': '(Wokwy) quochuy.software@gmail.com + claude.ai',
    'website': 'http://quanghuygroup.com/',
    'license': 'AGPL-3',
    'depends': [
        'product',
        'sale',
        'connector',
        'component',
        'queue_job',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/shopee_product_view.xml',
        'views/shopee_category_view.xml',
        'views/shopee_sale_order_view.xml',
        'views/shopee_partner_view.xml',
        'wizards/views/shopee_export_products_wizards_view.xml',
        'wizards/views/shopee_import_order_wizards_view.xml',
        'wizards/views/shopee_import_products_wizard_view.xml',
        'views/shopee_backend_view.xml',
        'views/menus.xml',
    ],
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,
}