{
    'name': 'Odoo PrestaShop Connector',
    'version': '17.0.1.0.0',
    'category': 'Connector',
    'summary': 'Connect and sync Odoo with PrestaShop',
    'author': '(Wokwy) quochuy.software@gmail.com + claude.ai',
    'website': 'https://c2bgroup.com',
    'license': 'AGPL-3',
    'depends': [
        'base',
        'sale',
        'stock',
        'product',
        'connector',
        'queue_job',
    ],
    'external_dependencies': {
        'python': [
            'prestapyt',
            'cachetools',
            'packaging',
        ],
    },
    'data': [
        'security/ir.model.access.csv',
        'views/prestashop_backend_views.xml',
        'views/prestashop_shop_views.xml',
        'views/prestashop_tax_views.xml',
        'views/product_template_views.xml',
        'views/product_category_views.xml',
        'views/res_partner_views.xml',
        'views/sale_order_views.xml',
        'views/stock_picking_views.xml',
        'views/prestashop_order_sync_view.xml',
        'wizards/import_products_view.xml',
        'wizards/export_products_view.xml',
        'wizards/export_categories_view.xml',
        'views/menus.xml',
        'data/ir_cron_data.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}