{
    'name': 'WooCommerce Connector',
    'version': '17.0.1.0.0',
    'category': 'Connector',
    'summary': 'Connect Odoo with WooCommerce',
    'author': '(Wokwy) quochuy.software@gmail.com + claude.ai',
    'website': 'http://quanghuygroup.com/',
    'website': 'https://www.yourwebsite.com',
    'license': 'AGPL-3',
    'depends': [
        'base',
        'sale_management',
        'product',
        'stock',
        'connector',
        'component',
        'component_event',
        'queue_job',
    ],
    'external_dependencies': {
        'python': ['woocommerce'],
    },
    'data': [
        'security/ir.model.access.csv',
        'views/backend_view.xml',
        'views/product_view.xml',
        'views/sale_order_view.xml',
        'views/partner_view.xml',
        'views/menu.xml',
    ],
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,
}